spring:
  config:
    activate:
      on-profile: des
  application: gateway
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: users_service
          uri: http://172.18.0.20:3003/
          predicates:
            - Path= /user/**
        - id: tasks_service
          uri: http://172.18.0.21:3005/
          predicates:
            - Path= /tasks/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_URI}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_URI}/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_URI}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_URI}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI}
          jwk-set-uri: ${KEYCLOAK_URI}/protocol/openid-connect/certs

server:
  port: 8085
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
management:
  server:
    port: 9095
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings

gateway:
  resource:
    client:
      jwtUrl: ${KEYCLOAK_URI}/protocol/openid-connect/token
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}
      grantType: password
      scope: "profile email"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG